AWSTemplateFormatVersion: '2010-09-09'
Description: Mi primer lambda en platzi

Parameters:
	NombreLambda:
		Description: Nombre de la funcion Lambda
		Type: String

	RuntimeLambda:
		Description: Ingresa el runtime de la funcion lambda
		Type: String
		Default: python3.10
		AllowedValues:
			-python3.7
			-python2.7
			-ruby2.5
			-nodejs8.10
			-java8
			-dotnetcore2.1

Resources:
	LambdaPlatzi:
		Type: AWS:Serverless:Function
		Properties: 
			FunctionName: !Ref NombreLambda
			Handler: lambda_function.lambda_handler
			Runtime: !Ref RuntimeLambda
			MemoriSize: 512
			TimeOut: 600
			Role: !GetAtt LambdaRolePlatzi.arn

Outputs: 
	LambdaARN:
		Description: "ARN de la funcion Lambda"
		Value:
			!GetAtt LambdaPlatzi.arn
		Export:
			Name: LambdaPlatziArn
	LambdaName:
		Description: "Nombre de la funcion Lambda"
		Value: 
			!Ref LambdaPlatzi
		Export:
			Name: LambdaPlatziName
